//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("GD_Model", "FK_GD_Documento_GD_Estado", "GD_Estado", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DemoMVC.Models.GD_Estado), "GD_Documento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DemoMVC.Models.GD_Documento), true)]
[assembly: EdmRelationshipAttribute("GD_Model", "FK_GD_Documento_GD_TipoDocumento", "GD_TipoDocumento", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DemoMVC.Models.GD_TipoDocumento), "GD_Documento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DemoMVC.Models.GD_Documento), true)]
[assembly: EdmRelationshipAttribute("GD_Model", "FK_GD_Documento_GPP_Proyecto", "GPP_Proyecto", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DemoMVC.Models.GPP_Proyecto), "GD_Documento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DemoMVC.Models.GD_Documento), true)]
[assembly: EdmRelationshipAttribute("GD_Model", "FK_GD_DocumentoHistorial_GD_Documento1", "GD_Documento", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DemoMVC.Models.GD_Documento), "GD_DocumentoHistorial", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DemoMVC.Models.GD_DocumentoHistorial), true)]
[assembly: EdmRelationshipAttribute("GD_Model", "FK_GD_DocumentoPerfilAcceso_GD_Documento", "GD_Documento", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DemoMVC.Models.GD_Documento), "GD_DocumentoPerfilAcceso", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DemoMVC.Models.GD_DocumentoPerfilAcceso), true)]
[assembly: EdmRelationshipAttribute("GD_Model", "FK_GD_DocumentoHistorial_GD_Estado", "GD_Estado", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DemoMVC.Models.GD_Estado), "GD_DocumentoHistorial", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DemoMVC.Models.GD_DocumentoHistorial), true)]

#endregion

namespace DemoMVC.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class GD_Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new GD_Entities object using the connection string found in the 'GD_Entities' section of the application configuration file.
        /// </summary>
        public GD_Entities() : base("name=GD_Entities", "GD_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GD_Entities object.
        /// </summary>
        public GD_Entities(string connectionString) : base(connectionString, "GD_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GD_Entities object.
        /// </summary>
        public GD_Entities(EntityConnection connection) : base(connection, "GD_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GD_Documento> GD_Documento
        {
            get
            {
                if ((_GD_Documento == null))
                {
                    _GD_Documento = base.CreateObjectSet<GD_Documento>("GD_Documento");
                }
                return _GD_Documento;
            }
        }
        private ObjectSet<GD_Documento> _GD_Documento;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GD_DocumentoHistorial> GD_DocumentoHistorial
        {
            get
            {
                if ((_GD_DocumentoHistorial == null))
                {
                    _GD_DocumentoHistorial = base.CreateObjectSet<GD_DocumentoHistorial>("GD_DocumentoHistorial");
                }
                return _GD_DocumentoHistorial;
            }
        }
        private ObjectSet<GD_DocumentoHistorial> _GD_DocumentoHistorial;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GD_DocumentoPerfilAcceso> GD_DocumentoPerfilAcceso
        {
            get
            {
                if ((_GD_DocumentoPerfilAcceso == null))
                {
                    _GD_DocumentoPerfilAcceso = base.CreateObjectSet<GD_DocumentoPerfilAcceso>("GD_DocumentoPerfilAcceso");
                }
                return _GD_DocumentoPerfilAcceso;
            }
        }
        private ObjectSet<GD_DocumentoPerfilAcceso> _GD_DocumentoPerfilAcceso;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GD_Estado> GD_Estado
        {
            get
            {
                if ((_GD_Estado == null))
                {
                    _GD_Estado = base.CreateObjectSet<GD_Estado>("GD_Estado");
                }
                return _GD_Estado;
            }
        }
        private ObjectSet<GD_Estado> _GD_Estado;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GD_TipoDocumento> GD_TipoDocumento
        {
            get
            {
                if ((_GD_TipoDocumento == null))
                {
                    _GD_TipoDocumento = base.CreateObjectSet<GD_TipoDocumento>("GD_TipoDocumento");
                }
                return _GD_TipoDocumento;
            }
        }
        private ObjectSet<GD_TipoDocumento> _GD_TipoDocumento;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GPP_Proyecto> GPP_Proyecto
        {
            get
            {
                if ((_GPP_Proyecto == null))
                {
                    _GPP_Proyecto = base.CreateObjectSet<GPP_Proyecto>("GPP_Proyecto");
                }
                return _GPP_Proyecto;
            }
        }
        private ObjectSet<GPP_Proyecto> _GPP_Proyecto;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GD_Documento EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGD_Documento(GD_Documento gD_Documento)
        {
            base.AddObject("GD_Documento", gD_Documento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GD_DocumentoHistorial EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGD_DocumentoHistorial(GD_DocumentoHistorial gD_DocumentoHistorial)
        {
            base.AddObject("GD_DocumentoHistorial", gD_DocumentoHistorial);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GD_DocumentoPerfilAcceso EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGD_DocumentoPerfilAcceso(GD_DocumentoPerfilAcceso gD_DocumentoPerfilAcceso)
        {
            base.AddObject("GD_DocumentoPerfilAcceso", gD_DocumentoPerfilAcceso);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GD_Estado EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGD_Estado(GD_Estado gD_Estado)
        {
            base.AddObject("GD_Estado", gD_Estado);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GD_TipoDocumento EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGD_TipoDocumento(GD_TipoDocumento gD_TipoDocumento)
        {
            base.AddObject("GD_TipoDocumento", gD_TipoDocumento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GPP_Proyecto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGPP_Proyecto(GPP_Proyecto gPP_Proyecto)
        {
            base.AddObject("GPP_Proyecto", gPP_Proyecto);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GD_Model", Name="GD_Documento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GD_Documento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GD_Documento object.
        /// </summary>
        /// <param name="idDocumento">Initial value of the IdDocumento property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="rutaFisica">Initial value of the RutaFisica property.</param>
        /// <param name="fechaRegistro">Initial value of the FechaRegistro property.</param>
        /// <param name="idEstado">Initial value of the IdEstado property.</param>
        /// <param name="idTipoDocumento">Initial value of the IdTipoDocumento property.</param>
        /// <param name="ubicacion">Initial value of the Ubicacion property.</param>
        public static GD_Documento CreateGD_Documento(global::System.Int32 idDocumento, global::System.String nombre, global::System.String rutaFisica, global::System.DateTime fechaRegistro, global::System.Int32 idEstado, global::System.Int32 idTipoDocumento, global::System.String ubicacion)
        {
            GD_Documento gD_Documento = new GD_Documento();
            gD_Documento.IdDocumento = idDocumento;
            gD_Documento.Nombre = nombre;
            gD_Documento.RutaFisica = rutaFisica;
            gD_Documento.FechaRegistro = fechaRegistro;
            gD_Documento.IdEstado = idEstado;
            gD_Documento.IdTipoDocumento = idTipoDocumento;
            gD_Documento.Ubicacion = ubicacion;
            return gD_Documento;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdDocumento
        {
            get
            {
                return _IdDocumento;
            }
            set
            {
                if (_IdDocumento != value)
                {
                    OnIdDocumentoChanging(value);
                    ReportPropertyChanging("IdDocumento");
                    _IdDocumento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdDocumento");
                    OnIdDocumentoChanged();
                }
            }
        }
        private global::System.Int32 _IdDocumento;
        partial void OnIdDocumentoChanging(global::System.Int32 value);
        partial void OnIdDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RutaFisica
        {
            get
            {
                return _RutaFisica;
            }
            set
            {
                OnRutaFisicaChanging(value);
                ReportPropertyChanging("RutaFisica");
                _RutaFisica = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RutaFisica");
                OnRutaFisicaChanged();
            }
        }
        private global::System.String _RutaFisica;
        partial void OnRutaFisicaChanging(global::System.String value);
        partial void OnRutaFisicaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tags
        {
            get
            {
                return _Tags;
            }
            set
            {
                OnTagsChanging(value);
                ReportPropertyChanging("Tags");
                _Tags = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tags");
                OnTagsChanged();
            }
        }
        private global::System.String _Tags;
        partial void OnTagsChanging(global::System.String value);
        partial void OnTagsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaRegistro
        {
            get
            {
                return _FechaRegistro;
            }
            set
            {
                OnFechaRegistroChanging(value);
                ReportPropertyChanging("FechaRegistro");
                _FechaRegistro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaRegistro");
                OnFechaRegistroChanged();
            }
        }
        private global::System.DateTime _FechaRegistro;
        partial void OnFechaRegistroChanging(global::System.DateTime value);
        partial void OnFechaRegistroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaDocumento
        {
            get
            {
                return _FechaDocumento;
            }
            set
            {
                OnFechaDocumentoChanging(value);
                ReportPropertyChanging("FechaDocumento");
                _FechaDocumento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaDocumento");
                OnFechaDocumentoChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaDocumento;
        partial void OnFechaDocumentoChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdProyecto
        {
            get
            {
                return _IdProyecto;
            }
            set
            {
                OnIdProyectoChanging(value);
                ReportPropertyChanging("IdProyecto");
                _IdProyecto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdProyecto");
                OnIdProyectoChanged();
            }
        }
        private Nullable<global::System.Int32> _IdProyecto;
        partial void OnIdProyectoChanging(Nullable<global::System.Int32> value);
        partial void OnIdProyectoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEstado
        {
            get
            {
                return _IdEstado;
            }
            set
            {
                OnIdEstadoChanging(value);
                ReportPropertyChanging("IdEstado");
                _IdEstado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEstado");
                OnIdEstadoChanged();
            }
        }
        private global::System.Int32 _IdEstado;
        partial void OnIdEstadoChanging(global::System.Int32 value);
        partial void OnIdEstadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdArea
        {
            get
            {
                return _IdArea;
            }
            set
            {
                OnIdAreaChanging(value);
                ReportPropertyChanging("IdArea");
                _IdArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdArea");
                OnIdAreaChanged();
            }
        }
        private Nullable<global::System.Int32> _IdArea;
        partial void OnIdAreaChanging(Nullable<global::System.Int32> value);
        partial void OnIdAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTipoDocumento
        {
            get
            {
                return _IdTipoDocumento;
            }
            set
            {
                OnIdTipoDocumentoChanging(value);
                ReportPropertyChanging("IdTipoDocumento");
                _IdTipoDocumento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTipoDocumento");
                OnIdTipoDocumentoChanged();
            }
        }
        private global::System.Int32 _IdTipoDocumento;
        partial void OnIdTipoDocumentoChanging(global::System.Int32 value);
        partial void OnIdTipoDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ubicacion
        {
            get
            {
                return _Ubicacion;
            }
            set
            {
                OnUbicacionChanging(value);
                ReportPropertyChanging("Ubicacion");
                _Ubicacion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ubicacion");
                OnUbicacionChanged();
            }
        }
        private global::System.String _Ubicacion;
        partial void OnUbicacionChanging(global::System.String value);
        partial void OnUbicacionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GD_Model", "FK_GD_Documento_GD_Estado", "GD_Estado")]
        public GD_Estado GD_Estado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GD_Estado>("GD_Model.FK_GD_Documento_GD_Estado", "GD_Estado").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GD_Estado>("GD_Model.FK_GD_Documento_GD_Estado", "GD_Estado").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GD_Estado> GD_EstadoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GD_Estado>("GD_Model.FK_GD_Documento_GD_Estado", "GD_Estado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GD_Estado>("GD_Model.FK_GD_Documento_GD_Estado", "GD_Estado", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GD_Model", "FK_GD_Documento_GD_TipoDocumento", "GD_TipoDocumento")]
        public GD_TipoDocumento GD_TipoDocumento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GD_TipoDocumento>("GD_Model.FK_GD_Documento_GD_TipoDocumento", "GD_TipoDocumento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GD_TipoDocumento>("GD_Model.FK_GD_Documento_GD_TipoDocumento", "GD_TipoDocumento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GD_TipoDocumento> GD_TipoDocumentoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GD_TipoDocumento>("GD_Model.FK_GD_Documento_GD_TipoDocumento", "GD_TipoDocumento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GD_TipoDocumento>("GD_Model.FK_GD_Documento_GD_TipoDocumento", "GD_TipoDocumento", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GD_Model", "FK_GD_Documento_GPP_Proyecto", "GPP_Proyecto")]
        public GPP_Proyecto GPP_Proyecto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GPP_Proyecto>("GD_Model.FK_GD_Documento_GPP_Proyecto", "GPP_Proyecto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GPP_Proyecto>("GD_Model.FK_GD_Documento_GPP_Proyecto", "GPP_Proyecto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GPP_Proyecto> GPP_ProyectoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GPP_Proyecto>("GD_Model.FK_GD_Documento_GPP_Proyecto", "GPP_Proyecto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GPP_Proyecto>("GD_Model.FK_GD_Documento_GPP_Proyecto", "GPP_Proyecto", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GD_Model", "FK_GD_DocumentoHistorial_GD_Documento1", "GD_DocumentoHistorial")]
        public EntityCollection<GD_DocumentoHistorial> GD_DocumentoHistorial
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GD_DocumentoHistorial>("GD_Model.FK_GD_DocumentoHistorial_GD_Documento1", "GD_DocumentoHistorial");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GD_DocumentoHistorial>("GD_Model.FK_GD_DocumentoHistorial_GD_Documento1", "GD_DocumentoHistorial", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GD_Model", "FK_GD_DocumentoPerfilAcceso_GD_Documento", "GD_DocumentoPerfilAcceso")]
        public EntityCollection<GD_DocumentoPerfilAcceso> GD_DocumentoPerfilAcceso
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GD_DocumentoPerfilAcceso>("GD_Model.FK_GD_DocumentoPerfilAcceso_GD_Documento", "GD_DocumentoPerfilAcceso");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GD_DocumentoPerfilAcceso>("GD_Model.FK_GD_DocumentoPerfilAcceso_GD_Documento", "GD_DocumentoPerfilAcceso", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GD_Model", Name="GD_DocumentoHistorial")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GD_DocumentoHistorial : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GD_DocumentoHistorial object.
        /// </summary>
        /// <param name="idDocumentoHistorial">Initial value of the IdDocumentoHistorial property.</param>
        /// <param name="idDocumento">Initial value of the IdDocumento property.</param>
        /// <param name="idUsuarioPerfil">Initial value of the IdUsuarioPerfil property.</param>
        /// <param name="fechaAcceso">Initial value of the FechaAcceso property.</param>
        /// <param name="idEstado">Initial value of the IdEstado property.</param>
        public static GD_DocumentoHistorial CreateGD_DocumentoHistorial(global::System.Int32 idDocumentoHistorial, global::System.Int32 idDocumento, global::System.Int32 idUsuarioPerfil, global::System.DateTime fechaAcceso, global::System.Int32 idEstado)
        {
            GD_DocumentoHistorial gD_DocumentoHistorial = new GD_DocumentoHistorial();
            gD_DocumentoHistorial.IdDocumentoHistorial = idDocumentoHistorial;
            gD_DocumentoHistorial.IdDocumento = idDocumento;
            gD_DocumentoHistorial.IdUsuarioPerfil = idUsuarioPerfil;
            gD_DocumentoHistorial.FechaAcceso = fechaAcceso;
            gD_DocumentoHistorial.IdEstado = idEstado;
            return gD_DocumentoHistorial;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdDocumentoHistorial
        {
            get
            {
                return _IdDocumentoHistorial;
            }
            set
            {
                if (_IdDocumentoHistorial != value)
                {
                    OnIdDocumentoHistorialChanging(value);
                    ReportPropertyChanging("IdDocumentoHistorial");
                    _IdDocumentoHistorial = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdDocumentoHistorial");
                    OnIdDocumentoHistorialChanged();
                }
            }
        }
        private global::System.Int32 _IdDocumentoHistorial;
        partial void OnIdDocumentoHistorialChanging(global::System.Int32 value);
        partial void OnIdDocumentoHistorialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdDocumento
        {
            get
            {
                return _IdDocumento;
            }
            set
            {
                OnIdDocumentoChanging(value);
                ReportPropertyChanging("IdDocumento");
                _IdDocumento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdDocumento");
                OnIdDocumentoChanged();
            }
        }
        private global::System.Int32 _IdDocumento;
        partial void OnIdDocumentoChanging(global::System.Int32 value);
        partial void OnIdDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuarioPerfil
        {
            get
            {
                return _IdUsuarioPerfil;
            }
            set
            {
                OnIdUsuarioPerfilChanging(value);
                ReportPropertyChanging("IdUsuarioPerfil");
                _IdUsuarioPerfil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdUsuarioPerfil");
                OnIdUsuarioPerfilChanged();
            }
        }
        private global::System.Int32 _IdUsuarioPerfil;
        partial void OnIdUsuarioPerfilChanging(global::System.Int32 value);
        partial void OnIdUsuarioPerfilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaAcceso
        {
            get
            {
                return _FechaAcceso;
            }
            set
            {
                OnFechaAccesoChanging(value);
                ReportPropertyChanging("FechaAcceso");
                _FechaAcceso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaAcceso");
                OnFechaAccesoChanged();
            }
        }
        private global::System.DateTime _FechaAcceso;
        partial void OnFechaAccesoChanging(global::System.DateTime value);
        partial void OnFechaAccesoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEstado
        {
            get
            {
                return _IdEstado;
            }
            set
            {
                OnIdEstadoChanging(value);
                ReportPropertyChanging("IdEstado");
                _IdEstado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEstado");
                OnIdEstadoChanged();
            }
        }
        private global::System.Int32 _IdEstado;
        partial void OnIdEstadoChanging(global::System.Int32 value);
        partial void OnIdEstadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GD_Model", "FK_GD_DocumentoHistorial_GD_Documento1", "GD_Documento")]
        public GD_Documento GD_Documento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GD_Documento>("GD_Model.FK_GD_DocumentoHistorial_GD_Documento1", "GD_Documento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GD_Documento>("GD_Model.FK_GD_DocumentoHistorial_GD_Documento1", "GD_Documento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GD_Documento> GD_DocumentoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GD_Documento>("GD_Model.FK_GD_DocumentoHistorial_GD_Documento1", "GD_Documento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GD_Documento>("GD_Model.FK_GD_DocumentoHistorial_GD_Documento1", "GD_Documento", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GD_Model", "FK_GD_DocumentoHistorial_GD_Estado", "GD_Estado")]
        public GD_Estado GD_Estado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GD_Estado>("GD_Model.FK_GD_DocumentoHistorial_GD_Estado", "GD_Estado").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GD_Estado>("GD_Model.FK_GD_DocumentoHistorial_GD_Estado", "GD_Estado").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GD_Estado> GD_EstadoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GD_Estado>("GD_Model.FK_GD_DocumentoHistorial_GD_Estado", "GD_Estado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GD_Estado>("GD_Model.FK_GD_DocumentoHistorial_GD_Estado", "GD_Estado", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GD_Model", Name="GD_DocumentoPerfilAcceso")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GD_DocumentoPerfilAcceso : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GD_DocumentoPerfilAcceso object.
        /// </summary>
        /// <param name="idDocPerfilAcceso">Initial value of the IdDocPerfilAcceso property.</param>
        /// <param name="idDocumento">Initial value of the IdDocumento property.</param>
        /// <param name="idPerfil">Initial value of the IdPerfil property.</param>
        public static GD_DocumentoPerfilAcceso CreateGD_DocumentoPerfilAcceso(global::System.Int32 idDocPerfilAcceso, global::System.Int32 idDocumento, global::System.Int32 idPerfil)
        {
            GD_DocumentoPerfilAcceso gD_DocumentoPerfilAcceso = new GD_DocumentoPerfilAcceso();
            gD_DocumentoPerfilAcceso.IdDocPerfilAcceso = idDocPerfilAcceso;
            gD_DocumentoPerfilAcceso.IdDocumento = idDocumento;
            gD_DocumentoPerfilAcceso.IdPerfil = idPerfil;
            return gD_DocumentoPerfilAcceso;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdDocPerfilAcceso
        {
            get
            {
                return _IdDocPerfilAcceso;
            }
            set
            {
                if (_IdDocPerfilAcceso != value)
                {
                    OnIdDocPerfilAccesoChanging(value);
                    ReportPropertyChanging("IdDocPerfilAcceso");
                    _IdDocPerfilAcceso = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdDocPerfilAcceso");
                    OnIdDocPerfilAccesoChanged();
                }
            }
        }
        private global::System.Int32 _IdDocPerfilAcceso;
        partial void OnIdDocPerfilAccesoChanging(global::System.Int32 value);
        partial void OnIdDocPerfilAccesoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdDocumento
        {
            get
            {
                return _IdDocumento;
            }
            set
            {
                OnIdDocumentoChanging(value);
                ReportPropertyChanging("IdDocumento");
                _IdDocumento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdDocumento");
                OnIdDocumentoChanged();
            }
        }
        private global::System.Int32 _IdDocumento;
        partial void OnIdDocumentoChanging(global::System.Int32 value);
        partial void OnIdDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPerfil
        {
            get
            {
                return _IdPerfil;
            }
            set
            {
                OnIdPerfilChanging(value);
                ReportPropertyChanging("IdPerfil");
                _IdPerfil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPerfil");
                OnIdPerfilChanged();
            }
        }
        private global::System.Int32 _IdPerfil;
        partial void OnIdPerfilChanging(global::System.Int32 value);
        partial void OnIdPerfilChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GD_Model", "FK_GD_DocumentoPerfilAcceso_GD_Documento", "GD_Documento")]
        public GD_Documento GD_Documento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GD_Documento>("GD_Model.FK_GD_DocumentoPerfilAcceso_GD_Documento", "GD_Documento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GD_Documento>("GD_Model.FK_GD_DocumentoPerfilAcceso_GD_Documento", "GD_Documento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GD_Documento> GD_DocumentoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GD_Documento>("GD_Model.FK_GD_DocumentoPerfilAcceso_GD_Documento", "GD_Documento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GD_Documento>("GD_Model.FK_GD_DocumentoPerfilAcceso_GD_Documento", "GD_Documento", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GD_Model", Name="GD_Estado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GD_Estado : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GD_Estado object.
        /// </summary>
        /// <param name="idEstado">Initial value of the IdEstado property.</param>
        public static GD_Estado CreateGD_Estado(global::System.Int32 idEstado)
        {
            GD_Estado gD_Estado = new GD_Estado();
            gD_Estado.IdEstado = idEstado;
            return gD_Estado;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEstado
        {
            get
            {
                return _IdEstado;
            }
            set
            {
                if (_IdEstado != value)
                {
                    OnIdEstadoChanging(value);
                    ReportPropertyChanging("IdEstado");
                    _IdEstado = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdEstado");
                    OnIdEstadoChanged();
                }
            }
        }
        private global::System.Int32 _IdEstado;
        partial void OnIdEstadoChanging(global::System.Int32 value);
        partial void OnIdEstadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GD_Model", "FK_GD_Documento_GD_Estado", "GD_Documento")]
        public EntityCollection<GD_Documento> GD_Documento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GD_Documento>("GD_Model.FK_GD_Documento_GD_Estado", "GD_Documento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GD_Documento>("GD_Model.FK_GD_Documento_GD_Estado", "GD_Documento", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GD_Model", "FK_GD_DocumentoHistorial_GD_Estado", "GD_DocumentoHistorial")]
        public EntityCollection<GD_DocumentoHistorial> GD_DocumentoHistorial
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GD_DocumentoHistorial>("GD_Model.FK_GD_DocumentoHistorial_GD_Estado", "GD_DocumentoHistorial");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GD_DocumentoHistorial>("GD_Model.FK_GD_DocumentoHistorial_GD_Estado", "GD_DocumentoHistorial", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GD_Model", Name="GD_TipoDocumento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GD_TipoDocumento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GD_TipoDocumento object.
        /// </summary>
        /// <param name="idTipoDocumento">Initial value of the IdTipoDocumento property.</param>
        public static GD_TipoDocumento CreateGD_TipoDocumento(global::System.Int32 idTipoDocumento)
        {
            GD_TipoDocumento gD_TipoDocumento = new GD_TipoDocumento();
            gD_TipoDocumento.IdTipoDocumento = idTipoDocumento;
            return gD_TipoDocumento;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTipoDocumento
        {
            get
            {
                return _IdTipoDocumento;
            }
            set
            {
                if (_IdTipoDocumento != value)
                {
                    OnIdTipoDocumentoChanging(value);
                    ReportPropertyChanging("IdTipoDocumento");
                    _IdTipoDocumento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdTipoDocumento");
                    OnIdTipoDocumentoChanged();
                }
            }
        }
        private global::System.Int32 _IdTipoDocumento;
        partial void OnIdTipoDocumentoChanging(global::System.Int32 value);
        partial void OnIdTipoDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Vigencia
        {
            get
            {
                return _Vigencia;
            }
            set
            {
                OnVigenciaChanging(value);
                ReportPropertyChanging("Vigencia");
                _Vigencia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Vigencia");
                OnVigenciaChanged();
            }
        }
        private Nullable<global::System.Int16> _Vigencia;
        partial void OnVigenciaChanging(Nullable<global::System.Int16> value);
        partial void OnVigenciaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GD_Model", "FK_GD_Documento_GD_TipoDocumento", "GD_Documento")]
        public EntityCollection<GD_Documento> GD_Documento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GD_Documento>("GD_Model.FK_GD_Documento_GD_TipoDocumento", "GD_Documento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GD_Documento>("GD_Model.FK_GD_Documento_GD_TipoDocumento", "GD_Documento", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GD_Model", Name="GPP_Proyecto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GPP_Proyecto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GPP_Proyecto object.
        /// </summary>
        /// <param name="idProyecto">Initial value of the IdProyecto property.</param>
        public static GPP_Proyecto CreateGPP_Proyecto(global::System.Int32 idProyecto)
        {
            GPP_Proyecto gPP_Proyecto = new GPP_Proyecto();
            gPP_Proyecto.IdProyecto = idProyecto;
            return gPP_Proyecto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProyecto
        {
            get
            {
                return _IdProyecto;
            }
            set
            {
                if (_IdProyecto != value)
                {
                    OnIdProyectoChanging(value);
                    ReportPropertyChanging("IdProyecto");
                    _IdProyecto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdProyecto");
                    OnIdProyectoChanged();
                }
            }
        }
        private global::System.Int32 _IdProyecto;
        partial void OnIdProyectoChanging(global::System.Int32 value);
        partial void OnIdProyectoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NroHojaEnvio
        {
            get
            {
                return _NroHojaEnvio;
            }
            set
            {
                OnNroHojaEnvioChanging(value);
                ReportPropertyChanging("NroHojaEnvio");
                _NroHojaEnvio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NroHojaEnvio");
                OnNroHojaEnvioChanged();
            }
        }
        private global::System.String _NroHojaEnvio;
        partial void OnNroHojaEnvioChanging(global::System.String value);
        partial void OnNroHojaEnvioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaHojaEnvio
        {
            get
            {
                return _FechaHojaEnvio;
            }
            set
            {
                OnFechaHojaEnvioChanging(value);
                ReportPropertyChanging("FechaHojaEnvio");
                _FechaHojaEnvio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaHojaEnvio");
                OnFechaHojaEnvioChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaHojaEnvio;
        partial void OnFechaHojaEnvioChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaHojaEnvioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaInicioPlaneada
        {
            get
            {
                return _FechaInicioPlaneada;
            }
            set
            {
                OnFechaInicioPlaneadaChanging(value);
                ReportPropertyChanging("FechaInicioPlaneada");
                _FechaInicioPlaneada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaInicioPlaneada");
                OnFechaInicioPlaneadaChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaInicioPlaneada;
        partial void OnFechaInicioPlaneadaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaInicioPlaneadaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaFinPlaneada
        {
            get
            {
                return _FechaFinPlaneada;
            }
            set
            {
                OnFechaFinPlaneadaChanging(value);
                ReportPropertyChanging("FechaFinPlaneada");
                _FechaFinPlaneada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaFinPlaneada");
                OnFechaFinPlaneadaChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaFinPlaneada;
        partial void OnFechaFinPlaneadaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaFinPlaneadaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaInicioReal
        {
            get
            {
                return _FechaInicioReal;
            }
            set
            {
                OnFechaInicioRealChanging(value);
                ReportPropertyChanging("FechaInicioReal");
                _FechaInicioReal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaInicioReal");
                OnFechaInicioRealChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaInicioReal;
        partial void OnFechaInicioRealChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaInicioRealChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaFinReal
        {
            get
            {
                return _FechaFinReal;
            }
            set
            {
                OnFechaFinRealChanging(value);
                ReportPropertyChanging("FechaFinReal");
                _FechaFinReal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaFinReal");
                OnFechaFinRealChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaFinReal;
        partial void OnFechaFinRealChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaFinRealChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CondicionPago
        {
            get
            {
                return _CondicionPago;
            }
            set
            {
                OnCondicionPagoChanging(value);
                ReportPropertyChanging("CondicionPago");
                _CondicionPago = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CondicionPago");
                OnCondicionPagoChanged();
            }
        }
        private global::System.String _CondicionPago;
        partial void OnCondicionPagoChanging(global::System.String value);
        partial void OnCondicionPagoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RazonSocial
        {
            get
            {
                return _RazonSocial;
            }
            set
            {
                OnRazonSocialChanging(value);
                ReportPropertyChanging("RazonSocial");
                _RazonSocial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RazonSocial");
                OnRazonSocialChanged();
            }
        }
        private global::System.String _RazonSocial;
        partial void OnRazonSocialChanging(global::System.String value);
        partial void OnRazonSocialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ruc
        {
            get
            {
                return _Ruc;
            }
            set
            {
                OnRucChanging(value);
                ReportPropertyChanging("Ruc");
                _Ruc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ruc");
                OnRucChanged();
            }
        }
        private global::System.String _Ruc;
        partial void OnRucChanging(global::System.String value);
        partial void OnRucChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Prioridad
        {
            get
            {
                return _Prioridad;
            }
            set
            {
                OnPrioridadChanging(value);
                ReportPropertyChanging("Prioridad");
                _Prioridad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prioridad");
                OnPrioridadChanged();
            }
        }
        private Nullable<global::System.Int32> _Prioridad;
        partial void OnPrioridadChanging(Nullable<global::System.Int32> value);
        partial void OnPrioridadChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GD_Model", "FK_GD_Documento_GPP_Proyecto", "GD_Documento")]
        public EntityCollection<GD_Documento> GD_Documento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GD_Documento>("GD_Model.FK_GD_Documento_GPP_Proyecto", "GD_Documento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GD_Documento>("GD_Model.FK_GD_Documento_GPP_Proyecto", "GD_Documento", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
