//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("PMPDBModel", "FK_PMP_DetallePptoMtoPreventivo_PMP_MaquinariaEquipo", "PMP_MaquinariaEquipo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DemoMVC.Models.PMP_MaquinariaEquipo), "PMP_DetallePptoMtoPreventivo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DemoMVC.Models.PMP_DetallePptoMtoPreventivo), true)]
[assembly: EdmRelationshipAttribute("PMPDBModel", "FK_PMP_DetallePptoMtoPreventivo_PMP_PptoMtoPreventivo", "PMP_PptoMtoPreventivo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DemoMVC.Models.PMP_PptoMtoPreventivo), "PMP_DetallePptoMtoPreventivo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DemoMVC.Models.PMP_DetallePptoMtoPreventivo), true)]
[assembly: EdmRelationshipAttribute("PMPDBModel", "FK_PMP_DetalleProgramacionPreventiva_PMP_ProgramacionPreventiva", "PMP_ProgramacionPreventiva", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DemoMVC.Models.PMP_ProgramacionPreventiva), "PMP_DetalleProgramacionPreventiva", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DemoMVC.Models.PMP_DetalleProgramacionPreventiva), true)]
[assembly: EdmRelationshipAttribute("PMPDBModel", "FK_PMP_ProgramacionPreventiva_PMP_MaquinariaEquipo", "PMP_MaquinariaEquipo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DemoMVC.Models.PMP_MaquinariaEquipo), "PMP_ProgramacionPreventiva", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DemoMVC.Models.PMP_ProgramacionPreventiva), true)]
[assembly: EdmRelationshipAttribute("PMPDBModel", "FK_PMP_ProgramacionPreventiva_PMP_PptoMtoPreventivo", "PMP_PptoMtoPreventivo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DemoMVC.Models.PMP_PptoMtoPreventivo), "PMP_ProgramacionPreventiva", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DemoMVC.Models.PMP_ProgramacionPreventiva), true)]

#endregion

namespace DemoMVC.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PMP_Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PMP_Entities object using the connection string found in the 'PMP_Entities' section of the application configuration file.
        /// </summary>
        public PMP_Entities() : base("name=PMP_Entities", "PMP_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PMP_Entities object.
        /// </summary>
        public PMP_Entities(string connectionString) : base(connectionString, "PMP_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PMP_Entities object.
        /// </summary>
        public PMP_Entities(EntityConnection connection) : base(connection, "PMP_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PMP_DetallePptoMtoPreventivo> PMP_DetallePptoMtoPreventivo
        {
            get
            {
                if ((_PMP_DetallePptoMtoPreventivo == null))
                {
                    _PMP_DetallePptoMtoPreventivo = base.CreateObjectSet<PMP_DetallePptoMtoPreventivo>("PMP_DetallePptoMtoPreventivo");
                }
                return _PMP_DetallePptoMtoPreventivo;
            }
        }
        private ObjectSet<PMP_DetallePptoMtoPreventivo> _PMP_DetallePptoMtoPreventivo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PMP_DetalleProgramacionPreventiva> PMP_DetalleProgramacionPreventiva
        {
            get
            {
                if ((_PMP_DetalleProgramacionPreventiva == null))
                {
                    _PMP_DetalleProgramacionPreventiva = base.CreateObjectSet<PMP_DetalleProgramacionPreventiva>("PMP_DetalleProgramacionPreventiva");
                }
                return _PMP_DetalleProgramacionPreventiva;
            }
        }
        private ObjectSet<PMP_DetalleProgramacionPreventiva> _PMP_DetalleProgramacionPreventiva;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PMP_MaquinariaEquipo> PMP_MaquinariaEquipo
        {
            get
            {
                if ((_PMP_MaquinariaEquipo == null))
                {
                    _PMP_MaquinariaEquipo = base.CreateObjectSet<PMP_MaquinariaEquipo>("PMP_MaquinariaEquipo");
                }
                return _PMP_MaquinariaEquipo;
            }
        }
        private ObjectSet<PMP_MaquinariaEquipo> _PMP_MaquinariaEquipo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PMP_PptoMtoPreventivo> PMP_PptoMtoPreventivo
        {
            get
            {
                if ((_PMP_PptoMtoPreventivo == null))
                {
                    _PMP_PptoMtoPreventivo = base.CreateObjectSet<PMP_PptoMtoPreventivo>("PMP_PptoMtoPreventivo");
                }
                return _PMP_PptoMtoPreventivo;
            }
        }
        private ObjectSet<PMP_PptoMtoPreventivo> _PMP_PptoMtoPreventivo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PMP_ProgramacionPreventiva> PMP_ProgramacionPreventiva
        {
            get
            {
                if ((_PMP_ProgramacionPreventiva == null))
                {
                    _PMP_ProgramacionPreventiva = base.CreateObjectSet<PMP_ProgramacionPreventiva>("PMP_ProgramacionPreventiva");
                }
                return _PMP_ProgramacionPreventiva;
            }
        }
        private ObjectSet<PMP_ProgramacionPreventiva> _PMP_ProgramacionPreventiva;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PMP_DetallePptoMtoPreventivo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPMP_DetallePptoMtoPreventivo(PMP_DetallePptoMtoPreventivo pMP_DetallePptoMtoPreventivo)
        {
            base.AddObject("PMP_DetallePptoMtoPreventivo", pMP_DetallePptoMtoPreventivo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PMP_DetalleProgramacionPreventiva EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPMP_DetalleProgramacionPreventiva(PMP_DetalleProgramacionPreventiva pMP_DetalleProgramacionPreventiva)
        {
            base.AddObject("PMP_DetalleProgramacionPreventiva", pMP_DetalleProgramacionPreventiva);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PMP_MaquinariaEquipo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPMP_MaquinariaEquipo(PMP_MaquinariaEquipo pMP_MaquinariaEquipo)
        {
            base.AddObject("PMP_MaquinariaEquipo", pMP_MaquinariaEquipo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PMP_PptoMtoPreventivo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPMP_PptoMtoPreventivo(PMP_PptoMtoPreventivo pMP_PptoMtoPreventivo)
        {
            base.AddObject("PMP_PptoMtoPreventivo", pMP_PptoMtoPreventivo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PMP_ProgramacionPreventiva EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPMP_ProgramacionPreventiva(PMP_ProgramacionPreventiva pMP_ProgramacionPreventiva)
        {
            base.AddObject("PMP_ProgramacionPreventiva", pMP_ProgramacionPreventiva);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PMPDBModel", Name="PMP_DetallePptoMtoPreventivo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PMP_DetallePptoMtoPreventivo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PMP_DetallePptoMtoPreventivo object.
        /// </summary>
        /// <param name="idDetallePptoMtoPreventivo">Initial value of the idDetallePptoMtoPreventivo property.</param>
        /// <param name="idPptoMtoPreventivo">Initial value of the idPptoMtoPreventivo property.</param>
        /// <param name="idMaquinariaEquipo">Initial value of the idMaquinariaEquipo property.</param>
        public static PMP_DetallePptoMtoPreventivo CreatePMP_DetallePptoMtoPreventivo(global::System.Int32 idDetallePptoMtoPreventivo, global::System.Int32 idPptoMtoPreventivo, global::System.Int32 idMaquinariaEquipo)
        {
            PMP_DetallePptoMtoPreventivo pMP_DetallePptoMtoPreventivo = new PMP_DetallePptoMtoPreventivo();
            pMP_DetallePptoMtoPreventivo.idDetallePptoMtoPreventivo = idDetallePptoMtoPreventivo;
            pMP_DetallePptoMtoPreventivo.idPptoMtoPreventivo = idPptoMtoPreventivo;
            pMP_DetallePptoMtoPreventivo.idMaquinariaEquipo = idMaquinariaEquipo;
            return pMP_DetallePptoMtoPreventivo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idDetallePptoMtoPreventivo
        {
            get
            {
                return _idDetallePptoMtoPreventivo;
            }
            set
            {
                if (_idDetallePptoMtoPreventivo != value)
                {
                    OnidDetallePptoMtoPreventivoChanging(value);
                    ReportPropertyChanging("idDetallePptoMtoPreventivo");
                    _idDetallePptoMtoPreventivo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idDetallePptoMtoPreventivo");
                    OnidDetallePptoMtoPreventivoChanged();
                }
            }
        }
        private global::System.Int32 _idDetallePptoMtoPreventivo;
        partial void OnidDetallePptoMtoPreventivoChanging(global::System.Int32 value);
        partial void OnidDetallePptoMtoPreventivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idPptoMtoPreventivo
        {
            get
            {
                return _idPptoMtoPreventivo;
            }
            set
            {
                OnidPptoMtoPreventivoChanging(value);
                ReportPropertyChanging("idPptoMtoPreventivo");
                _idPptoMtoPreventivo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idPptoMtoPreventivo");
                OnidPptoMtoPreventivoChanged();
            }
        }
        private global::System.Int32 _idPptoMtoPreventivo;
        partial void OnidPptoMtoPreventivoChanging(global::System.Int32 value);
        partial void OnidPptoMtoPreventivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idMaquinariaEquipo
        {
            get
            {
                return _idMaquinariaEquipo;
            }
            set
            {
                OnidMaquinariaEquipoChanging(value);
                ReportPropertyChanging("idMaquinariaEquipo");
                _idMaquinariaEquipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idMaquinariaEquipo");
                OnidMaquinariaEquipoChanged();
            }
        }
        private global::System.Int32 _idMaquinariaEquipo;
        partial void OnidMaquinariaEquipoChanging(global::System.Int32 value);
        partial void OnidMaquinariaEquipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> cantidadMantenimiento
        {
            get
            {
                return _cantidadMantenimiento;
            }
            set
            {
                OncantidadMantenimientoChanging(value);
                ReportPropertyChanging("cantidadMantenimiento");
                _cantidadMantenimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidadMantenimiento");
                OncantidadMantenimientoChanged();
            }
        }
        private Nullable<global::System.Decimal> _cantidadMantenimiento;
        partial void OncantidadMantenimientoChanging(Nullable<global::System.Decimal> value);
        partial void OncantidadMantenimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> montoAprobado
        {
            get
            {
                return _montoAprobado;
            }
            set
            {
                OnmontoAprobadoChanging(value);
                ReportPropertyChanging("montoAprobado");
                _montoAprobado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("montoAprobado");
                OnmontoAprobadoChanged();
            }
        }
        private Nullable<global::System.Decimal> _montoAprobado;
        partial void OnmontoAprobadoChanging(Nullable<global::System.Decimal> value);
        partial void OnmontoAprobadoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PMPDBModel", "FK_PMP_DetallePptoMtoPreventivo_PMP_MaquinariaEquipo", "PMP_MaquinariaEquipo")]
        public PMP_MaquinariaEquipo PMP_MaquinariaEquipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PMP_MaquinariaEquipo>("PMPDBModel.FK_PMP_DetallePptoMtoPreventivo_PMP_MaquinariaEquipo", "PMP_MaquinariaEquipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PMP_MaquinariaEquipo>("PMPDBModel.FK_PMP_DetallePptoMtoPreventivo_PMP_MaquinariaEquipo", "PMP_MaquinariaEquipo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PMP_MaquinariaEquipo> PMP_MaquinariaEquipoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PMP_MaquinariaEquipo>("PMPDBModel.FK_PMP_DetallePptoMtoPreventivo_PMP_MaquinariaEquipo", "PMP_MaquinariaEquipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PMP_MaquinariaEquipo>("PMPDBModel.FK_PMP_DetallePptoMtoPreventivo_PMP_MaquinariaEquipo", "PMP_MaquinariaEquipo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PMPDBModel", "FK_PMP_DetallePptoMtoPreventivo_PMP_PptoMtoPreventivo", "PMP_PptoMtoPreventivo")]
        public PMP_PptoMtoPreventivo PMP_PptoMtoPreventivo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PMP_PptoMtoPreventivo>("PMPDBModel.FK_PMP_DetallePptoMtoPreventivo_PMP_PptoMtoPreventivo", "PMP_PptoMtoPreventivo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PMP_PptoMtoPreventivo>("PMPDBModel.FK_PMP_DetallePptoMtoPreventivo_PMP_PptoMtoPreventivo", "PMP_PptoMtoPreventivo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PMP_PptoMtoPreventivo> PMP_PptoMtoPreventivoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PMP_PptoMtoPreventivo>("PMPDBModel.FK_PMP_DetallePptoMtoPreventivo_PMP_PptoMtoPreventivo", "PMP_PptoMtoPreventivo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PMP_PptoMtoPreventivo>("PMPDBModel.FK_PMP_DetallePptoMtoPreventivo_PMP_PptoMtoPreventivo", "PMP_PptoMtoPreventivo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PMPDBModel", Name="PMP_DetalleProgramacionPreventiva")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PMP_DetalleProgramacionPreventiva : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PMP_DetalleProgramacionPreventiva object.
        /// </summary>
        /// <param name="idDetalleProgramacionPreventiva">Initial value of the idDetalleProgramacionPreventiva property.</param>
        public static PMP_DetalleProgramacionPreventiva CreatePMP_DetalleProgramacionPreventiva(global::System.Int32 idDetalleProgramacionPreventiva)
        {
            PMP_DetalleProgramacionPreventiva pMP_DetalleProgramacionPreventiva = new PMP_DetalleProgramacionPreventiva();
            pMP_DetalleProgramacionPreventiva.idDetalleProgramacionPreventiva = idDetalleProgramacionPreventiva;
            return pMP_DetalleProgramacionPreventiva;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idDetalleProgramacionPreventiva
        {
            get
            {
                return _idDetalleProgramacionPreventiva;
            }
            set
            {
                if (_idDetalleProgramacionPreventiva != value)
                {
                    OnidDetalleProgramacionPreventivaChanging(value);
                    ReportPropertyChanging("idDetalleProgramacionPreventiva");
                    _idDetalleProgramacionPreventiva = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idDetalleProgramacionPreventiva");
                    OnidDetalleProgramacionPreventivaChanged();
                }
            }
        }
        private global::System.Int32 _idDetalleProgramacionPreventiva;
        partial void OnidDetalleProgramacionPreventivaChanging(global::System.Int32 value);
        partial void OnidDetalleProgramacionPreventivaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idProgramacionPreventiva
        {
            get
            {
                return _idProgramacionPreventiva;
            }
            set
            {
                OnidProgramacionPreventivaChanging(value);
                ReportPropertyChanging("idProgramacionPreventiva");
                _idProgramacionPreventiva = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idProgramacionPreventiva");
                OnidProgramacionPreventivaChanged();
            }
        }
        private Nullable<global::System.Int32> _idProgramacionPreventiva;
        partial void OnidProgramacionPreventivaChanging(Nullable<global::System.Int32> value);
        partial void OnidProgramacionPreventivaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> numeroProgramacion
        {
            get
            {
                return _numeroProgramacion;
            }
            set
            {
                OnnumeroProgramacionChanging(value);
                ReportPropertyChanging("numeroProgramacion");
                _numeroProgramacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numeroProgramacion");
                OnnumeroProgramacionChanged();
            }
        }
        private Nullable<global::System.Int32> _numeroProgramacion;
        partial void OnnumeroProgramacionChanging(Nullable<global::System.Int32> value);
        partial void OnnumeroProgramacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fechaProgramacion
        {
            get
            {
                return _fechaProgramacion;
            }
            set
            {
                OnfechaProgramacionChanging(value);
                ReportPropertyChanging("fechaProgramacion");
                _fechaProgramacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaProgramacion");
                OnfechaProgramacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _fechaProgramacion;
        partial void OnfechaProgramacionChanging(Nullable<global::System.DateTime> value);
        partial void OnfechaProgramacionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PMPDBModel", "FK_PMP_DetalleProgramacionPreventiva_PMP_ProgramacionPreventiva", "PMP_ProgramacionPreventiva")]
        public PMP_ProgramacionPreventiva PMP_ProgramacionPreventiva
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PMP_ProgramacionPreventiva>("PMPDBModel.FK_PMP_DetalleProgramacionPreventiva_PMP_ProgramacionPreventiva", "PMP_ProgramacionPreventiva").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PMP_ProgramacionPreventiva>("PMPDBModel.FK_PMP_DetalleProgramacionPreventiva_PMP_ProgramacionPreventiva", "PMP_ProgramacionPreventiva").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PMP_ProgramacionPreventiva> PMP_ProgramacionPreventivaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PMP_ProgramacionPreventiva>("PMPDBModel.FK_PMP_DetalleProgramacionPreventiva_PMP_ProgramacionPreventiva", "PMP_ProgramacionPreventiva");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PMP_ProgramacionPreventiva>("PMPDBModel.FK_PMP_DetalleProgramacionPreventiva_PMP_ProgramacionPreventiva", "PMP_ProgramacionPreventiva", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PMPDBModel", Name="PMP_MaquinariaEquipo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PMP_MaquinariaEquipo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PMP_MaquinariaEquipo object.
        /// </summary>
        /// <param name="idMaquinariaEquipo">Initial value of the idMaquinariaEquipo property.</param>
        public static PMP_MaquinariaEquipo CreatePMP_MaquinariaEquipo(global::System.Int32 idMaquinariaEquipo)
        {
            PMP_MaquinariaEquipo pMP_MaquinariaEquipo = new PMP_MaquinariaEquipo();
            pMP_MaquinariaEquipo.idMaquinariaEquipo = idMaquinariaEquipo;
            return pMP_MaquinariaEquipo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idMaquinariaEquipo
        {
            get
            {
                return _idMaquinariaEquipo;
            }
            set
            {
                if (_idMaquinariaEquipo != value)
                {
                    OnidMaquinariaEquipoChanging(value);
                    ReportPropertyChanging("idMaquinariaEquipo");
                    _idMaquinariaEquipo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idMaquinariaEquipo");
                    OnidMaquinariaEquipoChanged();
                }
            }
        }
        private global::System.Int32 _idMaquinariaEquipo;
        partial void OnidMaquinariaEquipoChanging(global::System.Int32 value);
        partial void OnidMaquinariaEquipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String marca
        {
            get
            {
                return _marca;
            }
            set
            {
                OnmarcaChanging(value);
                ReportPropertyChanging("marca");
                _marca = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("marca");
                OnmarcaChanged();
            }
        }
        private global::System.String _marca;
        partial void OnmarcaChanging(global::System.String value);
        partial void OnmarcaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modelo
        {
            get
            {
                return _modelo;
            }
            set
            {
                OnmodeloChanging(value);
                ReportPropertyChanging("modelo");
                _modelo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modelo");
                OnmodeloChanged();
            }
        }
        private global::System.String _modelo;
        partial void OnmodeloChanging(global::System.String value);
        partial void OnmodeloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> anoFabricacion
        {
            get
            {
                return _anoFabricacion;
            }
            set
            {
                OnanoFabricacionChanging(value);
                ReportPropertyChanging("anoFabricacion");
                _anoFabricacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("anoFabricacion");
                OnanoFabricacionChanged();
            }
        }
        private Nullable<global::System.Int32> _anoFabricacion;
        partial void OnanoFabricacionChanging(Nullable<global::System.Int32> value);
        partial void OnanoFabricacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fechaRegistro
        {
            get
            {
                return _fechaRegistro;
            }
            set
            {
                OnfechaRegistroChanging(value);
                ReportPropertyChanging("fechaRegistro");
                _fechaRegistro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaRegistro");
                OnfechaRegistroChanged();
            }
        }
        private Nullable<global::System.DateTime> _fechaRegistro;
        partial void OnfechaRegistroChanging(Nullable<global::System.DateTime> value);
        partial void OnfechaRegistroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fechaBaja
        {
            get
            {
                return _fechaBaja;
            }
            set
            {
                OnfechaBajaChanging(value);
                ReportPropertyChanging("fechaBaja");
                _fechaBaja = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaBaja");
                OnfechaBajaChanged();
            }
        }
        private Nullable<global::System.DateTime> _fechaBaja;
        partial void OnfechaBajaChanging(Nullable<global::System.DateTime> value);
        partial void OnfechaBajaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fechaExpiracionGarantia
        {
            get
            {
                return _fechaExpiracionGarantia;
            }
            set
            {
                OnfechaExpiracionGarantiaChanging(value);
                ReportPropertyChanging("fechaExpiracionGarantia");
                _fechaExpiracionGarantia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaExpiracionGarantia");
                OnfechaExpiracionGarantiaChanged();
            }
        }
        private Nullable<global::System.DateTime> _fechaExpiracionGarantia;
        partial void OnfechaExpiracionGarantiaChanging(Nullable<global::System.DateTime> value);
        partial void OnfechaExpiracionGarantiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> costoMantenimiento
        {
            get
            {
                return _costoMantenimiento;
            }
            set
            {
                OncostoMantenimientoChanging(value);
                ReportPropertyChanging("costoMantenimiento");
                _costoMantenimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("costoMantenimiento");
                OncostoMantenimientoChanged();
            }
        }
        private Nullable<global::System.Decimal> _costoMantenimiento;
        partial void OncostoMantenimientoChanging(Nullable<global::System.Decimal> value);
        partial void OncostoMantenimientoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PMPDBModel", "FK_PMP_DetallePptoMtoPreventivo_PMP_MaquinariaEquipo", "PMP_DetallePptoMtoPreventivo")]
        public EntityCollection<PMP_DetallePptoMtoPreventivo> PMP_DetallePptoMtoPreventivo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PMP_DetallePptoMtoPreventivo>("PMPDBModel.FK_PMP_DetallePptoMtoPreventivo_PMP_MaquinariaEquipo", "PMP_DetallePptoMtoPreventivo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PMP_DetallePptoMtoPreventivo>("PMPDBModel.FK_PMP_DetallePptoMtoPreventivo_PMP_MaquinariaEquipo", "PMP_DetallePptoMtoPreventivo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PMPDBModel", "FK_PMP_ProgramacionPreventiva_PMP_MaquinariaEquipo", "PMP_ProgramacionPreventiva")]
        public EntityCollection<PMP_ProgramacionPreventiva> PMP_ProgramacionPreventiva
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PMP_ProgramacionPreventiva>("PMPDBModel.FK_PMP_ProgramacionPreventiva_PMP_MaquinariaEquipo", "PMP_ProgramacionPreventiva");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PMP_ProgramacionPreventiva>("PMPDBModel.FK_PMP_ProgramacionPreventiva_PMP_MaquinariaEquipo", "PMP_ProgramacionPreventiva", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PMPDBModel", Name="PMP_PptoMtoPreventivo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PMP_PptoMtoPreventivo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PMP_PptoMtoPreventivo object.
        /// </summary>
        /// <param name="idPptoMtoPreventivo">Initial value of the idPptoMtoPreventivo property.</param>
        public static PMP_PptoMtoPreventivo CreatePMP_PptoMtoPreventivo(global::System.Int32 idPptoMtoPreventivo)
        {
            PMP_PptoMtoPreventivo pMP_PptoMtoPreventivo = new PMP_PptoMtoPreventivo();
            pMP_PptoMtoPreventivo.idPptoMtoPreventivo = idPptoMtoPreventivo;
            return pMP_PptoMtoPreventivo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idPptoMtoPreventivo
        {
            get
            {
                return _idPptoMtoPreventivo;
            }
            set
            {
                if (_idPptoMtoPreventivo != value)
                {
                    OnidPptoMtoPreventivoChanging(value);
                    ReportPropertyChanging("idPptoMtoPreventivo");
                    _idPptoMtoPreventivo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idPptoMtoPreventivo");
                    OnidPptoMtoPreventivoChanged();
                }
            }
        }
        private global::System.Int32 _idPptoMtoPreventivo;
        partial void OnidPptoMtoPreventivoChanging(global::System.Int32 value);
        partial void OnidPptoMtoPreventivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ano
        {
            get
            {
                return _ano;
            }
            set
            {
                OnanoChanging(value);
                ReportPropertyChanging("ano");
                _ano = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ano");
                OnanoChanged();
            }
        }
        private Nullable<global::System.Int32> _ano;
        partial void OnanoChanging(Nullable<global::System.Int32> value);
        partial void OnanoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> montoEstimado
        {
            get
            {
                return _montoEstimado;
            }
            set
            {
                OnmontoEstimadoChanging(value);
                ReportPropertyChanging("montoEstimado");
                _montoEstimado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("montoEstimado");
                OnmontoEstimadoChanged();
            }
        }
        private Nullable<global::System.Decimal> _montoEstimado;
        partial void OnmontoEstimadoChanging(Nullable<global::System.Decimal> value);
        partial void OnmontoEstimadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> montoFinal
        {
            get
            {
                return _montoFinal;
            }
            set
            {
                OnmontoFinalChanging(value);
                ReportPropertyChanging("montoFinal");
                _montoFinal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("montoFinal");
                OnmontoFinalChanged();
            }
        }
        private Nullable<global::System.Decimal> _montoFinal;
        partial void OnmontoFinalChanging(Nullable<global::System.Decimal> value);
        partial void OnmontoFinalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> cantidadMantencion
        {
            get
            {
                return _cantidadMantencion;
            }
            set
            {
                OncantidadMantencionChanging(value);
                ReportPropertyChanging("cantidadMantencion");
                _cantidadMantencion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidadMantencion");
                OncantidadMantencionChanged();
            }
        }
        private Nullable<global::System.Int32> _cantidadMantencion;
        partial void OncantidadMantencionChanging(Nullable<global::System.Int32> value);
        partial void OncantidadMantencionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fechaRegistro
        {
            get
            {
                return _fechaRegistro;
            }
            set
            {
                OnfechaRegistroChanging(value);
                ReportPropertyChanging("fechaRegistro");
                _fechaRegistro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaRegistro");
                OnfechaRegistroChanged();
            }
        }
        private Nullable<global::System.DateTime> _fechaRegistro;
        partial void OnfechaRegistroChanging(Nullable<global::System.DateTime> value);
        partial void OnfechaRegistroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.String _estado;
        partial void OnestadoChanging(global::System.String value);
        partial void OnestadoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PMPDBModel", "FK_PMP_DetallePptoMtoPreventivo_PMP_PptoMtoPreventivo", "PMP_DetallePptoMtoPreventivo")]
        public EntityCollection<PMP_DetallePptoMtoPreventivo> PMP_DetallePptoMtoPreventivo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PMP_DetallePptoMtoPreventivo>("PMPDBModel.FK_PMP_DetallePptoMtoPreventivo_PMP_PptoMtoPreventivo", "PMP_DetallePptoMtoPreventivo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PMP_DetallePptoMtoPreventivo>("PMPDBModel.FK_PMP_DetallePptoMtoPreventivo_PMP_PptoMtoPreventivo", "PMP_DetallePptoMtoPreventivo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PMPDBModel", "FK_PMP_ProgramacionPreventiva_PMP_PptoMtoPreventivo", "PMP_ProgramacionPreventiva")]
        public EntityCollection<PMP_ProgramacionPreventiva> PMP_ProgramacionPreventiva
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PMP_ProgramacionPreventiva>("PMPDBModel.FK_PMP_ProgramacionPreventiva_PMP_PptoMtoPreventivo", "PMP_ProgramacionPreventiva");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PMP_ProgramacionPreventiva>("PMPDBModel.FK_PMP_ProgramacionPreventiva_PMP_PptoMtoPreventivo", "PMP_ProgramacionPreventiva", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PMPDBModel", Name="PMP_ProgramacionPreventiva")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PMP_ProgramacionPreventiva : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PMP_ProgramacionPreventiva object.
        /// </summary>
        /// <param name="idProgramacionPreventiva">Initial value of the idProgramacionPreventiva property.</param>
        public static PMP_ProgramacionPreventiva CreatePMP_ProgramacionPreventiva(global::System.Int32 idProgramacionPreventiva)
        {
            PMP_ProgramacionPreventiva pMP_ProgramacionPreventiva = new PMP_ProgramacionPreventiva();
            pMP_ProgramacionPreventiva.idProgramacionPreventiva = idProgramacionPreventiva;
            return pMP_ProgramacionPreventiva;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idProgramacionPreventiva
        {
            get
            {
                return _idProgramacionPreventiva;
            }
            set
            {
                if (_idProgramacionPreventiva != value)
                {
                    OnidProgramacionPreventivaChanging(value);
                    ReportPropertyChanging("idProgramacionPreventiva");
                    _idProgramacionPreventiva = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idProgramacionPreventiva");
                    OnidProgramacionPreventivaChanged();
                }
            }
        }
        private global::System.Int32 _idProgramacionPreventiva;
        partial void OnidProgramacionPreventivaChanging(global::System.Int32 value);
        partial void OnidProgramacionPreventivaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idMaquinariaEquipo
        {
            get
            {
                return _idMaquinariaEquipo;
            }
            set
            {
                OnidMaquinariaEquipoChanging(value);
                ReportPropertyChanging("idMaquinariaEquipo");
                _idMaquinariaEquipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idMaquinariaEquipo");
                OnidMaquinariaEquipoChanged();
            }
        }
        private Nullable<global::System.Int32> _idMaquinariaEquipo;
        partial void OnidMaquinariaEquipoChanging(Nullable<global::System.Int32> value);
        partial void OnidMaquinariaEquipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idPptoMtoPreventivo
        {
            get
            {
                return _idPptoMtoPreventivo;
            }
            set
            {
                OnidPptoMtoPreventivoChanging(value);
                ReportPropertyChanging("idPptoMtoPreventivo");
                _idPptoMtoPreventivo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idPptoMtoPreventivo");
                OnidPptoMtoPreventivoChanged();
            }
        }
        private Nullable<global::System.Int32> _idPptoMtoPreventivo;
        partial void OnidPptoMtoPreventivoChanging(Nullable<global::System.Int32> value);
        partial void OnidPptoMtoPreventivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> cantidadMantenimientos
        {
            get
            {
                return _cantidadMantenimientos;
            }
            set
            {
                OncantidadMantenimientosChanging(value);
                ReportPropertyChanging("cantidadMantenimientos");
                _cantidadMantenimientos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidadMantenimientos");
                OncantidadMantenimientosChanged();
            }
        }
        private Nullable<global::System.Int32> _cantidadMantenimientos;
        partial void OncantidadMantenimientosChanging(Nullable<global::System.Int32> value);
        partial void OncantidadMantenimientosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fechaMaxima
        {
            get
            {
                return _fechaMaxima;
            }
            set
            {
                OnfechaMaximaChanging(value);
                ReportPropertyChanging("fechaMaxima");
                _fechaMaxima = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaMaxima");
                OnfechaMaximaChanged();
            }
        }
        private Nullable<global::System.DateTime> _fechaMaxima;
        partial void OnfechaMaximaChanging(Nullable<global::System.DateTime> value);
        partial void OnfechaMaximaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> maximaCantidadMantenimientos
        {
            get
            {
                return _maximaCantidadMantenimientos;
            }
            set
            {
                OnmaximaCantidadMantenimientosChanging(value);
                ReportPropertyChanging("maximaCantidadMantenimientos");
                _maximaCantidadMantenimientos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("maximaCantidadMantenimientos");
                OnmaximaCantidadMantenimientosChanged();
            }
        }
        private Nullable<global::System.Int32> _maximaCantidadMantenimientos;
        partial void OnmaximaCantidadMantenimientosChanging(Nullable<global::System.Int32> value);
        partial void OnmaximaCantidadMantenimientosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String estadoActualEquipo
        {
            get
            {
                return _estadoActualEquipo;
            }
            set
            {
                OnestadoActualEquipoChanging(value);
                ReportPropertyChanging("estadoActualEquipo");
                _estadoActualEquipo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("estadoActualEquipo");
                OnestadoActualEquipoChanged();
            }
        }
        private global::System.String _estadoActualEquipo;
        partial void OnestadoActualEquipoChanging(global::System.String value);
        partial void OnestadoActualEquipoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PMPDBModel", "FK_PMP_DetalleProgramacionPreventiva_PMP_ProgramacionPreventiva", "PMP_DetalleProgramacionPreventiva")]
        public EntityCollection<PMP_DetalleProgramacionPreventiva> PMP_DetalleProgramacionPreventiva
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PMP_DetalleProgramacionPreventiva>("PMPDBModel.FK_PMP_DetalleProgramacionPreventiva_PMP_ProgramacionPreventiva", "PMP_DetalleProgramacionPreventiva");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PMP_DetalleProgramacionPreventiva>("PMPDBModel.FK_PMP_DetalleProgramacionPreventiva_PMP_ProgramacionPreventiva", "PMP_DetalleProgramacionPreventiva", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PMPDBModel", "FK_PMP_ProgramacionPreventiva_PMP_MaquinariaEquipo", "PMP_MaquinariaEquipo")]
        public PMP_MaquinariaEquipo PMP_MaquinariaEquipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PMP_MaquinariaEquipo>("PMPDBModel.FK_PMP_ProgramacionPreventiva_PMP_MaquinariaEquipo", "PMP_MaquinariaEquipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PMP_MaquinariaEquipo>("PMPDBModel.FK_PMP_ProgramacionPreventiva_PMP_MaquinariaEquipo", "PMP_MaquinariaEquipo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PMP_MaquinariaEquipo> PMP_MaquinariaEquipoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PMP_MaquinariaEquipo>("PMPDBModel.FK_PMP_ProgramacionPreventiva_PMP_MaquinariaEquipo", "PMP_MaquinariaEquipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PMP_MaquinariaEquipo>("PMPDBModel.FK_PMP_ProgramacionPreventiva_PMP_MaquinariaEquipo", "PMP_MaquinariaEquipo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PMPDBModel", "FK_PMP_ProgramacionPreventiva_PMP_PptoMtoPreventivo", "PMP_PptoMtoPreventivo")]
        public PMP_PptoMtoPreventivo PMP_PptoMtoPreventivo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PMP_PptoMtoPreventivo>("PMPDBModel.FK_PMP_ProgramacionPreventiva_PMP_PptoMtoPreventivo", "PMP_PptoMtoPreventivo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PMP_PptoMtoPreventivo>("PMPDBModel.FK_PMP_ProgramacionPreventiva_PMP_PptoMtoPreventivo", "PMP_PptoMtoPreventivo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PMP_PptoMtoPreventivo> PMP_PptoMtoPreventivoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PMP_PptoMtoPreventivo>("PMPDBModel.FK_PMP_ProgramacionPreventiva_PMP_PptoMtoPreventivo", "PMP_PptoMtoPreventivo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PMP_PptoMtoPreventivo>("PMPDBModel.FK_PMP_ProgramacionPreventiva_PMP_PptoMtoPreventivo", "PMP_PptoMtoPreventivo", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
