//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace DemoMVC.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PresupuestoEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PresupuestoEntities object using the connection string found in the 'PresupuestoEntities' section of the application configuration file.
        /// </summary>
        public PresupuestoEntities() : base("name=PresupuestoEntities", "PresupuestoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PresupuestoEntities object.
        /// </summary>
        public PresupuestoEntities(string connectionString) : base(connectionString, "PresupuestoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PresupuestoEntities object.
        /// </summary>
        public PresupuestoEntities(EntityConnection connection) : base(connection, "PresupuestoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Presupuesto> Presupuesto
        {
            get
            {
                if ((_Presupuesto == null))
                {
                    _Presupuesto = base.CreateObjectSet<Presupuesto>("Presupuesto");
                }
                return _Presupuesto;
            }
        }
        private ObjectSet<Presupuesto> _Presupuesto;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Presupuesto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPresupuesto(Presupuesto presupuesto)
        {
            base.AddObject("Presupuesto", presupuesto);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PresupuestoModel", Name="Presupuesto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Presupuesto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Presupuesto object.
        /// </summary>
        /// <param name="codPre">Initial value of the codPre property.</param>
        public static Presupuesto CreatePresupuesto(global::System.Int32 codPre)
        {
            Presupuesto presupuesto = new Presupuesto();
            presupuesto.codPre = codPre;
            return presupuesto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 codPre
        {
            get
            {
                return _codPre;
            }
            set
            {
                if (_codPre != value)
                {
                    OncodPreChanging(value);
                    ReportPropertyChanging("codPre");
                    _codPre = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("codPre");
                    OncodPreChanged();
                }
            }
        }
        private global::System.Int32 _codPre;
        partial void OncodPreChanging(global::System.Int32 value);
        partial void OncodPreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String verPre
        {
            get
            {
                return _verPre;
            }
            set
            {
                OnverPreChanging(value);
                ReportPropertyChanging("verPre");
                _verPre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("verPre");
                OnverPreChanged();
            }
        }
        private global::System.String _verPre;
        partial void OnverPreChanging(global::System.String value);
        partial void OnverPreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> monPre
        {
            get
            {
                return _monPre;
            }
            set
            {
                OnmonPreChanging(value);
                ReportPropertyChanging("monPre");
                _monPre = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("monPre");
                OnmonPreChanged();
            }
        }
        private Nullable<global::System.Decimal> _monPre;
        partial void OnmonPreChanging(Nullable<global::System.Decimal> value);
        partial void OnmonPreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> impPre
        {
            get
            {
                return _impPre;
            }
            set
            {
                OnimpPreChanging(value);
                ReportPropertyChanging("impPre");
                _impPre = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("impPre");
                OnimpPreChanged();
            }
        }
        private Nullable<global::System.Decimal> _impPre;
        partial void OnimpPreChanging(Nullable<global::System.Decimal> value);
        partial void OnimpPreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String estPre
        {
            get
            {
                return _estPre;
            }
            set
            {
                OnestPreChanging(value);
                ReportPropertyChanging("estPre");
                _estPre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("estPre");
                OnestPreChanged();
            }
        }
        private global::System.String _estPre;
        partial void OnestPreChanging(global::System.String value);
        partial void OnestPreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nroordejePre
        {
            get
            {
                return _nroordejePre;
            }
            set
            {
                OnnroordejePreChanging(value);
                ReportPropertyChanging("nroordejePre");
                _nroordejePre = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nroordejePre");
                OnnroordejePreChanged();
            }
        }
        private Nullable<global::System.Int32> _nroordejePre;
        partial void OnnroordejePreChanging(Nullable<global::System.Int32> value);
        partial void OnnroordejePreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> impconPre
        {
            get
            {
                return _impconPre;
            }
            set
            {
                OnimpconPreChanging(value);
                ReportPropertyChanging("impconPre");
                _impconPre = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("impconPre");
                OnimpconPreChanged();
            }
        }
        private Nullable<global::System.Decimal> _impconPre;
        partial void OnimpconPreChanging(Nullable<global::System.Decimal> value);
        partial void OnimpconPreChanged();

        #endregion
    
    }

    #endregion
    
}
