//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ModuloFinanciero.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class PresupuestoEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto PresupuestoEntities usando la cadena de conexión encontrada en la sección 'PresupuestoEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public PresupuestoEntities() : base("name=PresupuestoEntities", "PresupuestoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto PresupuestoEntities.
        /// </summary>
        public PresupuestoEntities(string connectionString) : base(connectionString, "PresupuestoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto PresupuestoEntities.
        /// </summary>
        public PresupuestoEntities(EntityConnection connection) : base(connection, "PresupuestoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Presupuesto> Presupuesto
        {
            get
            {
                if ((_Presupuesto == null))
                {
                    _Presupuesto = base.CreateObjectSet<Presupuesto>("Presupuesto");
                }
                return _Presupuesto;
            }
        }
        private ObjectSet<Presupuesto> _Presupuesto;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Presupuesto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPresupuesto(Presupuesto presupuesto)
        {
            base.AddObject("Presupuesto", presupuesto);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PresupuestoModel", Name="Presupuesto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Presupuesto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Presupuesto.
        /// </summary>
        /// <param name="codPre">Valor inicial de la propiedad codPre.</param>
        public static Presupuesto CreatePresupuesto(global::System.Int32 codPre)
        {
            Presupuesto presupuesto = new Presupuesto();
            presupuesto.codPre = codPre;
            return presupuesto;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 codPre
        {
            get
            {
                return _codPre;
            }
            set
            {
                if (_codPre != value)
                {
                    OncodPreChanging(value);
                    ReportPropertyChanging("codPre");
                    _codPre = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("codPre");
                    OncodPreChanged();
                }
            }
        }
        private global::System.Int32 _codPre;
        partial void OncodPreChanging(global::System.Int32 value);
        partial void OncodPreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String verPre
        {
            get
            {
                return _verPre;
            }
            set
            {
                OnverPreChanging(value);
                ReportPropertyChanging("verPre");
                _verPre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("verPre");
                OnverPreChanged();
            }
        }
        private global::System.String _verPre;
        partial void OnverPreChanging(global::System.String value);
        partial void OnverPreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> monPre
        {
            get
            {
                return _monPre;
            }
            set
            {
                OnmonPreChanging(value);
                ReportPropertyChanging("monPre");
                _monPre = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("monPre");
                OnmonPreChanged();
            }
        }
        private Nullable<global::System.Decimal> _monPre;
        partial void OnmonPreChanging(Nullable<global::System.Decimal> value);
        partial void OnmonPreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> impPre
        {
            get
            {
                return _impPre;
            }
            set
            {
                OnimpPreChanging(value);
                ReportPropertyChanging("impPre");
                _impPre = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("impPre");
                OnimpPreChanged();
            }
        }
        private Nullable<global::System.Decimal> _impPre;
        partial void OnimpPreChanging(Nullable<global::System.Decimal> value);
        partial void OnimpPreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String estPre
        {
            get
            {
                return _estPre;
            }
            set
            {
                OnestPreChanging(value);
                ReportPropertyChanging("estPre");
                _estPre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("estPre");
                OnestPreChanged();
            }
        }
        private global::System.String _estPre;
        partial void OnestPreChanging(global::System.String value);
        partial void OnestPreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nroordejePre
        {
            get
            {
                return _nroordejePre;
            }
            set
            {
                OnnroordejePreChanging(value);
                ReportPropertyChanging("nroordejePre");
                _nroordejePre = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nroordejePre");
                OnnroordejePreChanged();
            }
        }
        private Nullable<global::System.Int32> _nroordejePre;
        partial void OnnroordejePreChanging(Nullable<global::System.Int32> value);
        partial void OnnroordejePreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> impconPre
        {
            get
            {
                return _impconPre;
            }
            set
            {
                OnimpconPreChanging(value);
                ReportPropertyChanging("impconPre");
                _impconPre = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("impconPre");
                OnimpconPreChanged();
            }
        }
        private Nullable<global::System.Decimal> _impconPre;
        partial void OnimpconPreChanging(Nullable<global::System.Decimal> value);
        partial void OnimpconPreChanged();

        #endregion
    
    }

    #endregion
    
}
