//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("S10Model", "FK_Actividad_Cronograma", "S10Cronograma", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DemoMVC.Models.S10Cronograma), "S10Actividad", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DemoMVC.Models.S10Actividad), true)]
[assembly: EdmRelationshipAttribute("S10Model", "FK_DetallePartida_APU", "S10APU", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DemoMVC.Models.S10APU), "S10DetallePartida", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DemoMVC.Models.S10DetallePartida), true)]
[assembly: EdmRelationshipAttribute("S10Model", "FK_DetallePartida_Categoria", "S10Categoria", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DemoMVC.Models.S10Categoria), "S10DetallePartida", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DemoMVC.Models.S10DetallePartida), true)]
[assembly: EdmRelationshipAttribute("S10Model", "FK_Presupuesto_Cliente", "S10Cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DemoMVC.Models.S10Cliente), "S10Presupuesto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DemoMVC.Models.S10Presupuesto), true)]
[assembly: EdmRelationshipAttribute("S10Model", "FK_Cronograma_Presupuesto", "S10Presupuesto", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DemoMVC.Models.S10Presupuesto), "S10Cronograma", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DemoMVC.Models.S10Cronograma), true)]
[assembly: EdmRelationshipAttribute("S10Model", "FK_DetallePartida_Partida", "S10Partida", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DemoMVC.Models.S10Partida), "S10DetallePartida", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DemoMVC.Models.S10DetallePartida), true)]
[assembly: EdmRelationshipAttribute("S10Model", "FK_Presupuesto_Obra", "S10Obra", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DemoMVC.Models.S10Obra), "S10Presupuesto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DemoMVC.Models.S10Presupuesto), true)]
[assembly: EdmRelationshipAttribute("S10Model", "FK_Partida_Presupuesto", "S10Presupuesto", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DemoMVC.Models.S10Presupuesto), "S10Partida", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DemoMVC.Models.S10Partida), true)]

#endregion

namespace DemoMVC.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class S10_Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new S10_Entities object using the connection string found in the 'S10_Entities' section of the application configuration file.
        /// </summary>
        public S10_Entities() : base("name=S10_Entities", "S10_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new S10_Entities object.
        /// </summary>
        public S10_Entities(string connectionString) : base(connectionString, "S10_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new S10_Entities object.
        /// </summary>
        public S10_Entities(EntityConnection connection) : base(connection, "S10_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<S10Actividad> S10Actividad
        {
            get
            {
                if ((_S10Actividad == null))
                {
                    _S10Actividad = base.CreateObjectSet<S10Actividad>("S10Actividad");
                }
                return _S10Actividad;
            }
        }
        private ObjectSet<S10Actividad> _S10Actividad;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<S10APU> S10APU
        {
            get
            {
                if ((_S10APU == null))
                {
                    _S10APU = base.CreateObjectSet<S10APU>("S10APU");
                }
                return _S10APU;
            }
        }
        private ObjectSet<S10APU> _S10APU;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<S10Categoria> S10Categoria
        {
            get
            {
                if ((_S10Categoria == null))
                {
                    _S10Categoria = base.CreateObjectSet<S10Categoria>("S10Categoria");
                }
                return _S10Categoria;
            }
        }
        private ObjectSet<S10Categoria> _S10Categoria;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<S10Cliente> S10Cliente
        {
            get
            {
                if ((_S10Cliente == null))
                {
                    _S10Cliente = base.CreateObjectSet<S10Cliente>("S10Cliente");
                }
                return _S10Cliente;
            }
        }
        private ObjectSet<S10Cliente> _S10Cliente;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<S10Cronograma> S10Cronograma
        {
            get
            {
                if ((_S10Cronograma == null))
                {
                    _S10Cronograma = base.CreateObjectSet<S10Cronograma>("S10Cronograma");
                }
                return _S10Cronograma;
            }
        }
        private ObjectSet<S10Cronograma> _S10Cronograma;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<S10DetallePartida> S10DetallePartida
        {
            get
            {
                if ((_S10DetallePartida == null))
                {
                    _S10DetallePartida = base.CreateObjectSet<S10DetallePartida>("S10DetallePartida");
                }
                return _S10DetallePartida;
            }
        }
        private ObjectSet<S10DetallePartida> _S10DetallePartida;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<S10Obra> S10Obra
        {
            get
            {
                if ((_S10Obra == null))
                {
                    _S10Obra = base.CreateObjectSet<S10Obra>("S10Obra");
                }
                return _S10Obra;
            }
        }
        private ObjectSet<S10Obra> _S10Obra;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<S10Partida> S10Partida
        {
            get
            {
                if ((_S10Partida == null))
                {
                    _S10Partida = base.CreateObjectSet<S10Partida>("S10Partida");
                }
                return _S10Partida;
            }
        }
        private ObjectSet<S10Partida> _S10Partida;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<S10Presupuesto> S10Presupuesto
        {
            get
            {
                if ((_S10Presupuesto == null))
                {
                    _S10Presupuesto = base.CreateObjectSet<S10Presupuesto>("S10Presupuesto");
                }
                return _S10Presupuesto;
            }
        }
        private ObjectSet<S10Presupuesto> _S10Presupuesto;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the S10Actividad EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToS10Actividad(S10Actividad s10Actividad)
        {
            base.AddObject("S10Actividad", s10Actividad);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the S10APU EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToS10APU(S10APU s10APU)
        {
            base.AddObject("S10APU", s10APU);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the S10Categoria EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToS10Categoria(S10Categoria s10Categoria)
        {
            base.AddObject("S10Categoria", s10Categoria);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the S10Cliente EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToS10Cliente(S10Cliente s10Cliente)
        {
            base.AddObject("S10Cliente", s10Cliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the S10Cronograma EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToS10Cronograma(S10Cronograma s10Cronograma)
        {
            base.AddObject("S10Cronograma", s10Cronograma);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the S10DetallePartida EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToS10DetallePartida(S10DetallePartida s10DetallePartida)
        {
            base.AddObject("S10DetallePartida", s10DetallePartida);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the S10Obra EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToS10Obra(S10Obra s10Obra)
        {
            base.AddObject("S10Obra", s10Obra);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the S10Partida EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToS10Partida(S10Partida s10Partida)
        {
            base.AddObject("S10Partida", s10Partida);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the S10Presupuesto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToS10Presupuesto(S10Presupuesto s10Presupuesto)
        {
            base.AddObject("S10Presupuesto", s10Presupuesto);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="S10Model", Name="S10Actividad")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class S10Actividad : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new S10Actividad object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static S10Actividad CreateS10Actividad(global::System.Int32 id)
        {
            S10Actividad s10Actividad = new S10Actividad();
            s10Actividad.ID = id;
            return s10Actividad;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Responsable
        {
            get
            {
                return _Responsable;
            }
            set
            {
                OnResponsableChanging(value);
                ReportPropertyChanging("Responsable");
                _Responsable = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Responsable");
                OnResponsableChanged();
            }
        }
        private global::System.String _Responsable;
        partial void OnResponsableChanging(global::System.String value);
        partial void OnResponsableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Hito
        {
            get
            {
                return _Hito;
            }
            set
            {
                OnHitoChanging(value);
                ReportPropertyChanging("Hito");
                _Hito = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Hito");
                OnHitoChanged();
            }
        }
        private global::System.String _Hito;
        partial void OnHitoChanging(global::System.String value);
        partial void OnHitoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDCronograma
        {
            get
            {
                return _IDCronograma;
            }
            set
            {
                OnIDCronogramaChanging(value);
                ReportPropertyChanging("IDCronograma");
                _IDCronograma = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCronograma");
                OnIDCronogramaChanged();
            }
        }
        private Nullable<global::System.Int32> _IDCronograma;
        partial void OnIDCronogramaChanging(Nullable<global::System.Int32> value);
        partial void OnIDCronogramaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("S10Model", "FK_Actividad_Cronograma", "S10Cronograma")]
        public S10Cronograma S10Cronograma
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Cronograma>("S10Model.FK_Actividad_Cronograma", "S10Cronograma").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Cronograma>("S10Model.FK_Actividad_Cronograma", "S10Cronograma").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<S10Cronograma> S10CronogramaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Cronograma>("S10Model.FK_Actividad_Cronograma", "S10Cronograma");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<S10Cronograma>("S10Model.FK_Actividad_Cronograma", "S10Cronograma", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="S10Model", Name="S10APU")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class S10APU : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new S10APU object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static S10APU CreateS10APU(global::System.Int32 id)
        {
            S10APU s10APU = new S10APU();
            s10APU.ID = id;
            return s10APU;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UM
        {
            get
            {
                return _UM;
            }
            set
            {
                OnUMChanging(value);
                ReportPropertyChanging("UM");
                _UM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UM");
                OnUMChanged();
            }
        }
        private global::System.String _UM;
        partial void OnUMChanging(global::System.String value);
        partial void OnUMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private Nullable<global::System.Decimal> _Total;
        partial void OnTotalChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("S10Model", "FK_DetallePartida_APU", "S10DetallePartida")]
        public EntityCollection<S10DetallePartida> S10DetallePartida
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<S10DetallePartida>("S10Model.FK_DetallePartida_APU", "S10DetallePartida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<S10DetallePartida>("S10Model.FK_DetallePartida_APU", "S10DetallePartida", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="S10Model", Name="S10Categoria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class S10Categoria : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new S10Categoria object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static S10Categoria CreateS10Categoria(global::System.Int32 id)
        {
            S10Categoria s10Categoria = new S10Categoria();
            s10Categoria.ID = id;
            return s10Categoria;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("S10Model", "FK_DetallePartida_Categoria", "S10DetallePartida")]
        public EntityCollection<S10DetallePartida> S10DetallePartida
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<S10DetallePartida>("S10Model.FK_DetallePartida_Categoria", "S10DetallePartida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<S10DetallePartida>("S10Model.FK_DetallePartida_Categoria", "S10DetallePartida", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="S10Model", Name="S10Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class S10Cliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new S10Cliente object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static S10Cliente CreateS10Cliente(global::System.Int32 id)
        {
            S10Cliente s10Cliente = new S10Cliente();
            s10Cliente.ID = id;
            return s10Cliente;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RazonSocial
        {
            get
            {
                return _RazonSocial;
            }
            set
            {
                OnRazonSocialChanging(value);
                ReportPropertyChanging("RazonSocial");
                _RazonSocial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RazonSocial");
                OnRazonSocialChanged();
            }
        }
        private global::System.String _RazonSocial;
        partial void OnRazonSocialChanging(global::System.String value);
        partial void OnRazonSocialChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("S10Model", "FK_Presupuesto_Cliente", "S10Presupuesto")]
        public EntityCollection<S10Presupuesto> S10Presupuesto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<S10Presupuesto>("S10Model.FK_Presupuesto_Cliente", "S10Presupuesto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<S10Presupuesto>("S10Model.FK_Presupuesto_Cliente", "S10Presupuesto", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="S10Model", Name="S10Cronograma")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class S10Cronograma : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new S10Cronograma object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static S10Cronograma CreateS10Cronograma(global::System.Int32 id)
        {
            S10Cronograma s10Cronograma = new S10Cronograma();
            s10Cronograma.ID = id;
            return s10Cronograma;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaInicio
        {
            get
            {
                return _FechaInicio;
            }
            set
            {
                OnFechaInicioChanging(value);
                ReportPropertyChanging("FechaInicio");
                _FechaInicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaInicio");
                OnFechaInicioChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaInicio;
        partial void OnFechaInicioChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaInicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaFin
        {
            get
            {
                return _FechaFin;
            }
            set
            {
                OnFechaFinChanging(value);
                ReportPropertyChanging("FechaFin");
                _FechaFin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaFin");
                OnFechaFinChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaFin;
        partial void OnFechaFinChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaFinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Responsable
        {
            get
            {
                return _Responsable;
            }
            set
            {
                OnResponsableChanging(value);
                ReportPropertyChanging("Responsable");
                _Responsable = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Responsable");
                OnResponsableChanged();
            }
        }
        private global::System.String _Responsable;
        partial void OnResponsableChanging(global::System.String value);
        partial void OnResponsableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDPresupuesto
        {
            get
            {
                return _IDPresupuesto;
            }
            set
            {
                OnIDPresupuestoChanging(value);
                ReportPropertyChanging("IDPresupuesto");
                _IDPresupuesto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDPresupuesto");
                OnIDPresupuestoChanged();
            }
        }
        private Nullable<global::System.Int32> _IDPresupuesto;
        partial void OnIDPresupuestoChanging(Nullable<global::System.Int32> value);
        partial void OnIDPresupuestoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("S10Model", "FK_Actividad_Cronograma", "S10Actividad")]
        public EntityCollection<S10Actividad> S10Actividad
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<S10Actividad>("S10Model.FK_Actividad_Cronograma", "S10Actividad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<S10Actividad>("S10Model.FK_Actividad_Cronograma", "S10Actividad", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("S10Model", "FK_Cronograma_Presupuesto", "S10Presupuesto")]
        public S10Presupuesto S10Presupuesto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Presupuesto>("S10Model.FK_Cronograma_Presupuesto", "S10Presupuesto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Presupuesto>("S10Model.FK_Cronograma_Presupuesto", "S10Presupuesto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<S10Presupuesto> S10PresupuestoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Presupuesto>("S10Model.FK_Cronograma_Presupuesto", "S10Presupuesto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<S10Presupuesto>("S10Model.FK_Cronograma_Presupuesto", "S10Presupuesto", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="S10Model", Name="S10DetallePartida")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class S10DetallePartida : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new S10DetallePartida object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static S10DetallePartida CreateS10DetallePartida(global::System.Int32 id)
        {
            S10DetallePartida s10DetallePartida = new S10DetallePartida();
            s10DetallePartida.ID = id;
            return s10DetallePartida;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                OnCantidadChanging(value);
                ReportPropertyChanging("Cantidad");
                _Cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad");
                OnCantidadChanged();
            }
        }
        private Nullable<global::System.Decimal> _Cantidad;
        partial void OnCantidadChanging(Nullable<global::System.Decimal> value);
        partial void OnCantidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PrecioUnitarioReal
        {
            get
            {
                return _PrecioUnitarioReal;
            }
            set
            {
                OnPrecioUnitarioRealChanging(value);
                ReportPropertyChanging("PrecioUnitarioReal");
                _PrecioUnitarioReal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrecioUnitarioReal");
                OnPrecioUnitarioRealChanged();
            }
        }
        private Nullable<global::System.Decimal> _PrecioUnitarioReal;
        partial void OnPrecioUnitarioRealChanging(Nullable<global::System.Decimal> value);
        partial void OnPrecioUnitarioRealChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDPartida
        {
            get
            {
                return _IDPartida;
            }
            set
            {
                OnIDPartidaChanging(value);
                ReportPropertyChanging("IDPartida");
                _IDPartida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDPartida");
                OnIDPartidaChanged();
            }
        }
        private Nullable<global::System.Int32> _IDPartida;
        partial void OnIDPartidaChanging(Nullable<global::System.Int32> value);
        partial void OnIDPartidaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDCategoria
        {
            get
            {
                return _IDCategoria;
            }
            set
            {
                OnIDCategoriaChanging(value);
                ReportPropertyChanging("IDCategoria");
                _IDCategoria = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCategoria");
                OnIDCategoriaChanged();
            }
        }
        private Nullable<global::System.Int32> _IDCategoria;
        partial void OnIDCategoriaChanging(Nullable<global::System.Int32> value);
        partial void OnIDCategoriaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDAPU
        {
            get
            {
                return _IDAPU;
            }
            set
            {
                OnIDAPUChanging(value);
                ReportPropertyChanging("IDAPU");
                _IDAPU = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDAPU");
                OnIDAPUChanged();
            }
        }
        private Nullable<global::System.Int32> _IDAPU;
        partial void OnIDAPUChanging(Nullable<global::System.Int32> value);
        partial void OnIDAPUChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("S10Model", "FK_DetallePartida_APU", "S10APU")]
        public S10APU S10APU
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10APU>("S10Model.FK_DetallePartida_APU", "S10APU").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10APU>("S10Model.FK_DetallePartida_APU", "S10APU").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<S10APU> S10APUReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10APU>("S10Model.FK_DetallePartida_APU", "S10APU");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<S10APU>("S10Model.FK_DetallePartida_APU", "S10APU", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("S10Model", "FK_DetallePartida_Categoria", "S10Categoria")]
        public S10Categoria S10Categoria
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Categoria>("S10Model.FK_DetallePartida_Categoria", "S10Categoria").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Categoria>("S10Model.FK_DetallePartida_Categoria", "S10Categoria").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<S10Categoria> S10CategoriaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Categoria>("S10Model.FK_DetallePartida_Categoria", "S10Categoria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<S10Categoria>("S10Model.FK_DetallePartida_Categoria", "S10Categoria", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("S10Model", "FK_DetallePartida_Partida", "S10Partida")]
        public S10Partida S10Partida
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Partida>("S10Model.FK_DetallePartida_Partida", "S10Partida").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Partida>("S10Model.FK_DetallePartida_Partida", "S10Partida").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<S10Partida> S10PartidaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Partida>("S10Model.FK_DetallePartida_Partida", "S10Partida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<S10Partida>("S10Model.FK_DetallePartida_Partida", "S10Partida", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="S10Model", Name="S10Obra")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class S10Obra : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new S10Obra object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static S10Obra CreateS10Obra(global::System.Int32 id)
        {
            S10Obra s10Obra = new S10Obra();
            s10Obra.ID = id;
            return s10Obra;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("S10Model", "FK_Presupuesto_Obra", "S10Presupuesto")]
        public EntityCollection<S10Presupuesto> S10Presupuesto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<S10Presupuesto>("S10Model.FK_Presupuesto_Obra", "S10Presupuesto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<S10Presupuesto>("S10Model.FK_Presupuesto_Obra", "S10Presupuesto", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="S10Model", Name="S10Partida")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class S10Partida : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new S10Partida object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static S10Partida CreateS10Partida(global::System.Int32 id)
        {
            S10Partida s10Partida = new S10Partida();
            s10Partida.ID = id;
            return s10Partida;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UM
        {
            get
            {
                return _UM;
            }
            set
            {
                OnUMChanging(value);
                ReportPropertyChanging("UM");
                _UM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UM");
                OnUMChanged();
            }
        }
        private global::System.String _UM;
        partial void OnUMChanging(global::System.String value);
        partial void OnUMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private Nullable<global::System.Decimal> _Total;
        partial void OnTotalChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDPresupuesto
        {
            get
            {
                return _IDPresupuesto;
            }
            set
            {
                OnIDPresupuestoChanging(value);
                ReportPropertyChanging("IDPresupuesto");
                _IDPresupuesto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDPresupuesto");
                OnIDPresupuestoChanged();
            }
        }
        private Nullable<global::System.Int32> _IDPresupuesto;
        partial void OnIDPresupuestoChanging(Nullable<global::System.Int32> value);
        partial void OnIDPresupuestoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("S10Model", "FK_DetallePartida_Partida", "S10DetallePartida")]
        public EntityCollection<S10DetallePartida> S10DetallePartida
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<S10DetallePartida>("S10Model.FK_DetallePartida_Partida", "S10DetallePartida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<S10DetallePartida>("S10Model.FK_DetallePartida_Partida", "S10DetallePartida", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("S10Model", "FK_Partida_Presupuesto", "S10Presupuesto")]
        public S10Presupuesto S10Presupuesto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Presupuesto>("S10Model.FK_Partida_Presupuesto", "S10Presupuesto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Presupuesto>("S10Model.FK_Partida_Presupuesto", "S10Presupuesto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<S10Presupuesto> S10PresupuestoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Presupuesto>("S10Model.FK_Partida_Presupuesto", "S10Presupuesto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<S10Presupuesto>("S10Model.FK_Partida_Presupuesto", "S10Presupuesto", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="S10Model", Name="S10Presupuesto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class S10Presupuesto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new S10Presupuesto object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static S10Presupuesto CreateS10Presupuesto(global::System.Int32 id)
        {
            S10Presupuesto s10Presupuesto = new S10Presupuesto();
            s10Presupuesto.ID = id;
            return s10Presupuesto;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                OnNumeroChanging(value);
                ReportPropertyChanging("Numero");
                _Numero = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Numero");
                OnNumeroChanged();
            }
        }
        private global::System.String _Numero;
        partial void OnNumeroChanging(global::System.String value);
        partial void OnNumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaInicio
        {
            get
            {
                return _FechaInicio;
            }
            set
            {
                OnFechaInicioChanging(value);
                ReportPropertyChanging("FechaInicio");
                _FechaInicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaInicio");
                OnFechaInicioChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaInicio;
        partial void OnFechaInicioChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaInicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaFin
        {
            get
            {
                return _FechaFin;
            }
            set
            {
                OnFechaFinChanging(value);
                ReportPropertyChanging("FechaFin");
                _FechaFin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaFin");
                OnFechaFinChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaFin;
        partial void OnFechaFinChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaFinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaRegistro
        {
            get
            {
                return _FechaRegistro;
            }
            set
            {
                OnFechaRegistroChanging(value);
                ReportPropertyChanging("FechaRegistro");
                _FechaRegistro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaRegistro");
                OnFechaRegistroChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaRegistro;
        partial void OnFechaRegistroChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaRegistroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalPresupuesto
        {
            get
            {
                return _TotalPresupuesto;
            }
            set
            {
                OnTotalPresupuestoChanging(value);
                ReportPropertyChanging("TotalPresupuesto");
                _TotalPresupuesto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalPresupuesto");
                OnTotalPresupuestoChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalPresupuesto;
        partial void OnTotalPresupuestoChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalPresupuestoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SubTotalEjecutado
        {
            get
            {
                return _SubTotalEjecutado;
            }
            set
            {
                OnSubTotalEjecutadoChanging(value);
                ReportPropertyChanging("SubTotalEjecutado");
                _SubTotalEjecutado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SubTotalEjecutado");
                OnSubTotalEjecutadoChanged();
            }
        }
        private Nullable<global::System.Decimal> _SubTotalEjecutado;
        partial void OnSubTotalEjecutadoChanging(Nullable<global::System.Decimal> value);
        partial void OnSubTotalEjecutadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observaciones
        {
            get
            {
                return _Observaciones;
            }
            set
            {
                OnObservacionesChanging(value);
                ReportPropertyChanging("Observaciones");
                _Observaciones = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observaciones");
                OnObservacionesChanged();
            }
        }
        private global::System.String _Observaciones;
        partial void OnObservacionesChanging(global::System.String value);
        partial void OnObservacionesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDCliente
        {
            get
            {
                return _IDCliente;
            }
            set
            {
                OnIDClienteChanging(value);
                ReportPropertyChanging("IDCliente");
                _IDCliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCliente");
                OnIDClienteChanged();
            }
        }
        private Nullable<global::System.Int32> _IDCliente;
        partial void OnIDClienteChanging(Nullable<global::System.Int32> value);
        partial void OnIDClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDObra
        {
            get
            {
                return _IDObra;
            }
            set
            {
                OnIDObraChanging(value);
                ReportPropertyChanging("IDObra");
                _IDObra = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDObra");
                OnIDObraChanged();
            }
        }
        private Nullable<global::System.Int32> _IDObra;
        partial void OnIDObraChanging(Nullable<global::System.Int32> value);
        partial void OnIDObraChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("S10Model", "FK_Presupuesto_Cliente", "S10Cliente")]
        public S10Cliente S10Cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Cliente>("S10Model.FK_Presupuesto_Cliente", "S10Cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Cliente>("S10Model.FK_Presupuesto_Cliente", "S10Cliente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<S10Cliente> S10ClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Cliente>("S10Model.FK_Presupuesto_Cliente", "S10Cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<S10Cliente>("S10Model.FK_Presupuesto_Cliente", "S10Cliente", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("S10Model", "FK_Cronograma_Presupuesto", "S10Cronograma")]
        public EntityCollection<S10Cronograma> S10Cronograma
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<S10Cronograma>("S10Model.FK_Cronograma_Presupuesto", "S10Cronograma");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<S10Cronograma>("S10Model.FK_Cronograma_Presupuesto", "S10Cronograma", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("S10Model", "FK_Presupuesto_Obra", "S10Obra")]
        public S10Obra S10Obra
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Obra>("S10Model.FK_Presupuesto_Obra", "S10Obra").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Obra>("S10Model.FK_Presupuesto_Obra", "S10Obra").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<S10Obra> S10ObraReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<S10Obra>("S10Model.FK_Presupuesto_Obra", "S10Obra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<S10Obra>("S10Model.FK_Presupuesto_Obra", "S10Obra", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("S10Model", "FK_Partida_Presupuesto", "S10Partida")]
        public EntityCollection<S10Partida> S10Partida
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<S10Partida>("S10Model.FK_Partida_Presupuesto", "S10Partida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<S10Partida>("S10Model.FK_Partida_Presupuesto", "S10Partida", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
